// Generated by scripts/generate-migration-manifest.mjs from migrations/*.sql.
// Do not edit this file by hand.
export const expectedMigrations = [
  "0001_initial.sql",
  "0002_drafts.sql",
  "0003_identity_and_access.sql",
  "0004_usernames.sql",
  "0005_author_inventory.sql",
  "0006_snapshot_adoption.sql",
  "0007_library_snapshots.sql",
] as const;
