import { Schema } from "effect";
import { HttpApiSchema } from "effect/unstable/httpapi";

const errorResponse = <const Code extends string>(code: Code, status: number) =>
  Schema.Struct({ error: Schema.Literal(code) }).pipe(HttpApiSchema.status(status));

export const UnauthorizedResponse = errorResponse("unauthorized", 401);
export const InsufficientScopeResponse = errorResponse("insufficient_scope", 403);
export const SessionRequiredResponse = errorResponse("session_required", 403);
export const ForbiddenResponse = errorResponse("forbidden", 403);
export const InvalidCursorResponse = errorResponse("invalid_cursor", 400);
export const InvalidRequestResponse = errorResponse("invalid_request", 400);
export const ForbiddenOriginResponse = errorResponse("forbidden_origin", 403);
export const SkitNotFoundResponse = errorResponse("skit_not_found", 404);
export const DeleteRequiresPrivateResponse = errorResponse("delete_requires_private", 409);
export const ArchiveTooLargeResponse = errorResponse("archive_too_large", 413);
export const DraftNotFoundResponse = errorResponse("draft_not_found", 404);
export const StaleDraftRevisionResponse = errorResponse("stale_draft_revision", 409);
export const ReleaseConflictResponse = errorResponse("release_conflict", 409);
export const RateLimitedResponse = errorResponse("rate_limited", 429);
export const InvalidScopeResponse = errorResponse("INVALID_SCOPE", 400);
export const InvalidExpiryResponse = errorResponse("invalid_expiry", 400);
export const UnauthorizedPrincipalResponse = errorResponse("UNAUTHORIZED", 400);
export const TokenNotFoundResponse = errorResponse("token_not_found", 404);
export const TeamSessionRequiredResponse = errorResponse("SESSION_REQUIRED", 400);
export const InvalidTeamResponse = errorResponse("INVALID_TEAM", 400);
export const TeamConflictResponse = errorResponse("TEAM_CONFLICT", 409);
export const TeamForbiddenResponse = errorResponse("FORBIDDEN", 403);
export const PrincipalNotFoundResponse = errorResponse("PRINCIPAL_NOT_FOUND", 404);
export const OwnerRoleImmutableResponse = errorResponse("OWNER_ROLE_IMMUTABLE", 400);
export const MembershipNotFoundResponse = errorResponse("membership_not_found", 404);
export const LibraryNotFoundResponse = errorResponse("library_not_found", 404);
export const LibraryCreateFailedResponse = errorResponse("LIBRARY_CREATE_FAILED", 400);
export const RevisionConflictResponse = errorResponse("REVISION_CONFLICT", 409);
export const StorageFailureResponse = errorResponse("storage_failure", 500);

export const unauthorizedResponse = { error: "unauthorized" as const };
export const insufficientScopeResponse = { error: "insufficient_scope" as const };
export const sessionRequiredResponse = { error: "session_required" as const };
export const forbiddenResponse = { error: "forbidden" as const };
export const invalidCursorResponse = { error: "invalid_cursor" as const };
export const invalidRequestResponse = { error: "invalid_request" as const };
export const forbiddenOriginResponse = { error: "forbidden_origin" as const };
export const skitNotFoundResponse = { error: "skit_not_found" as const };
export const deleteRequiresPrivateResponse = { error: "delete_requires_private" as const };
export const archiveTooLargeResponse = { error: "archive_too_large" as const };
export const draftNotFoundResponse = { error: "draft_not_found" as const };
export const staleDraftRevisionResponse = { error: "stale_draft_revision" as const };
export const releaseConflictResponse = { error: "release_conflict" as const };
export const rateLimitedResponse = { error: "rate_limited" as const };
export const invalidScopeResponse = { error: "INVALID_SCOPE" as const };
export const invalidExpiryResponse = { error: "invalid_expiry" as const };
export const unauthorizedPrincipalResponse = { error: "UNAUTHORIZED" as const };
export const tokenNotFoundResponse = { error: "token_not_found" as const };
export const teamSessionRequiredResponse = { error: "SESSION_REQUIRED" as const };
export const invalidTeamResponse = { error: "INVALID_TEAM" as const };
export const teamConflictResponse = { error: "TEAM_CONFLICT" as const };
export const teamForbiddenResponse = { error: "FORBIDDEN" as const };
export const principalNotFoundResponse = { error: "PRINCIPAL_NOT_FOUND" as const };
export const ownerRoleImmutableResponse = { error: "OWNER_ROLE_IMMUTABLE" as const };
export const membershipNotFoundResponse = { error: "membership_not_found" as const };
export const libraryNotFoundResponse = { error: "library_not_found" as const };
export const libraryCreateFailedResponse = { error: "LIBRARY_CREATE_FAILED" as const };
export const revisionConflictResponse = { error: "REVISION_CONFLICT" as const };
export const storageFailureResponse = { error: "storage_failure" as const };
