import type { UsageReport } from "@smolai/skit-core";

export const emptyUsageStory: UsageReport = {
  window: { start: "2026-10-01T00:00:00.000Z", end: "2026-10-08T00:00:00.000Z" },
  project: null,
  rows: [],
  coverage: [],
  incomplete: false,
  durationMs: 0,
};
export const observedUsageStory: UsageReport = {
  ...emptyUsageStory,
  rows: [
    {
      name: "example",
      harness: "codex",
      path: "/synthetic/skills/example/SKILL.md",
      skillId: null,
      identity: "unmanaged",
      calls: 0,
      loads: 1,
      reads: 3,
      lastObservedAt: "2026-10-07T12:00:00.000Z",
    },
    {
      name: "example",
      harness: "claude-code",
      path: null,
      skillId: null,
      identity: "name-only",
      calls: 2,
      loads: 0,
      reads: 0,
      lastObservedAt: "2026-10-07T10:00:00.000Z",
    },
  ],
  coverage: [
    {
      harness: "codex",
      root: "/synthetic/codex/sessions",
      status: "available",
      files: 2,
      bytes: 1024,
      bytesRead: 1024,
      records: 12,
      windowRecords: 10,
      malformed: 0,
      undated: 0,
      undatedCandidates: 0,
      unsupported: 1,
      duplicates: 0,
      missingIds: 0,
      summaries: 1,
      mentions: 3,
      slashCommands: 0,
      oversizedLines: 0,
      skippedFiles: 0,
      unreadableFiles: 0,
      changedFiles: 0,
      unknownProjectRecords: 0,
    },
  ],
  incomplete: true,
  durationMs: 10,
};
